version: 2.1

orbs:
  android: circleci/android@2.3.0
  aws-cli: circleci/aws-cli@4.1.0

jobs:
  build-and-store:
    working_directory: ~/circleci_android_app
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      - run:
          name: change the permissions of gradlew
          command: chmod +x ./gradlew
      - run: gradle --version
      - run: java --version
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run: ./gradlew build
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: android_outputs
      - persist_to_workspace:
          root: ~/circleci_android_app
          paths:
            - app/build/outputs/apk/debug/app-debug.apk
  
  deploy-on-s3:
    parameters:
      s3BucketName: 
        type: string
        default: "devops-circleci-android-app-prod-us-east-1-007756798683"
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/circleci_android_app
      - aws-cli/setup:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: ${AWS_REGION_NAME}
      - run: aws s3 sync ~/circleci_android_app/app/build/outputs/apk/debug/ s3://<< parameters.s3BucketName >>/

workflows:
  version: 2.1
  build-store-and-deploy:
    jobs:
      - build-and-store
      - deploy-on-s3:
          s3BucketName: "devops-circleci-android-app-prod-us-east-1-007756798683"
          context: aws_access_variables
          requires:
            - build-and-store

