version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    working_directory: ~/code
    executor:
      name: android/android-machine
      tag: 2021.10.1
    # environment:
    #   JVM_OPTS: -Xmx4608m #-Xmx3200m
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run: gradle --version
      - run: java --version
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

# workflows:
